### ISSUE TITLE
White Spaces in password input

### ISSUE THREAD

**Issue by 4rjunc** [phasehq/console#307] opened 2024-07-27 21:36 UTC
### Describe the bug

Users can input whitespace in the password fields

### To Reproduce

1. Create a new account.
2. After creating the organization.
3. Enter whitespace in the create password fields.
4. The password will be created with whitespaces

### Expected behavior

Users should be restricted from entering whitespace

### Screenshots

<img width="823" alt="Screenshot 2024-07-28 at 02 59 32" src="https://github.com/user-attachments/assets/380e283f-5d47-4d2a-b7b6-e1b1b4231915">

### Platform you are having the issue on:
Web

### Additional context
This behaviour can cause

- Consistency: Whitespace can be inconsistent across different systems or input methods, leading to login issues.
- User Error: Users might accidentally include leading or trailing spaces, making it difficult to reproduce the password consistently.
- Security: Some systems might trim whitespace, potentially weakening the password or causing mismatches between what the user entered and what's stored.

**Comment by 4rjunc** [comment] 2024-07-27 23:07
@rohan-chaturvedi If this is an issue that needs to be fixed. Can you assign me this?

**Comment by rohan-chaturvedi** [comment] 2024-07-28 05:32
@4rjunc on second thought, let's not make this change. It might break the password unlock for existing users who have whitespace in their password.

**Comment by 4rjunc** [comment] 2024-07-28 06:12
@rohan-chaturvedi I see. The idea is to implement whitespace restrictions only for new password creation, not for existing password authentication. This strategy would prevent new users from including spaces in their passwords when they sign up, while still allowing current users to log in with their existing passwords that may contain whitespace.

**Comment by rohan-chaturvedi** [comment] 2024-07-28 06:19
Ah, good call. My mistake, re-opening this and assigning you!

**Comment by nimish-ks** [comment] 2024-07-28 06:37
we want users to use passphrases over passwords for the security benefits they provide. its quite common for passphrases to contain spaces, the benefits outweigh the likelihood of edge cases where errors in passport input could occur.

>     Consistency: Whitespace can be inconsistent across different systems or input methods, leading to login issues.
    User Error: Users might accidentally include leading or trailing spaces, making it difficult to reproduce the password consistently.
    Security: Some systems might trim whitespace, potentially weakening the password or causing mismatches between what the user entered and what's stored.

i am not sufficiently convinced by the above arguments against whitespaces in passwords.

at a high level, while deciding on a password policy, one need to carefully evaluate each rule for potential unintended consequences. well intentioned restrictions may inadvertently weaken security by prompting users to choose less secure alternatives or circumvent the policy entirely. think - banking website password policies xD

open to ideas. but closing this for now.

**Closed by nimish-ks** 2024-07-28 06:37 UTC
Labels: bug
