### ISSUE TITLE
bug: website crashes on opening inspect panel

### ISSUE THREAD

**Issue by nishaaannnt** [phasehq/console#305] opened 2024-07-27 08:42 UTC
### Describe the bug

After setting up locally in developer mode. Whenever we try to inspect the website, the site crashes. 

### To Reproduce

1. Setup Locally
2. Inspect the website in browser (I was using brave)
3. The website will crash
4. Close the inspect panel and refresh -> the website will be back running 

### Expected behavior

No crashes should happen when inspected. 
Also no such logs were visible to us that can help to understand the issue

### Screenshots

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/e7ba4133-9782-4e53-8ab8-3e4b1946a4df">

### Platform you are having the issue on:

Device - Both Windows and Mac.

**Comment by rohan-chaturvedi** [comment] 2024-07-27 08:53
Thanks for the bug report @nishaaannnt !

**Comment by nishaaannnt** [comment] 2024-07-27 10:37
@rohan-chaturvedi also happens in the live website.Please check it in console.phase.dev 
Am unable to get the bearer token for the API due to this :)

**Comment by rohan-chaturvedi** [comment] 2024-07-30 08:37
@nishaaannnt I'm unable to reproduce this after trying on several different devices. This seems like an issue specific to your dev setup, browser or machine. I'm closing this for now since it doesn't affect users, but if you get any more detail about this issue, feel free to drop it here and we can look into resolving it.

**Closed** 2024-07-30 08:39 UTC
Labels: bug
